# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
